version: '3.4'

services:
  stapi-worker:
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  rabbitmq:
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./.data/rabbitmq/data/:/var/lib/rabbitmq/
        - ./.data/rabbitmq/log/:/var/log/rabbitmq

  postgres:
    ports:
      - 5432:5432
    volumes:
      - ./.data/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres  